module.exports = {
  AlreadyActivatedError: 'already activated',
  ClientNotExistError: 'client not exist',
  CubePointAggregationFailedError: 'failed to aggregate cube point',
  CubePointNotExistError: 'cube point not exist',
  DuplicateKeyError: 'duplicate key',
  FileNotExistError: 'file not exist',
  InternalError: 'internal error, contact us',
  InvalidAppKeyError: 'invalid appKey',
  InvalidAppSecretError: 'invalid appSecret',
  InvalidApiKeyError: 'invalid apiKey',
  InvalidApiSecretError: 'invalid apiSecret',
  InvalidClientKeyError: 'invalid clientKey',
  InvalidClientSecretError: 'invalid clientSecret',
  InvalidPasswordResetCodeError: 'invalid password reset code',
  InvalidTokenError: 'invalid token',
  PasswordNotMatchError: 'password not match',
  PendingPoiPullRequestExistsError: 'pending poi pull request exists',
  Success: 'success',
  SystemBusyError: 'system busy, retry later',
  TokenExpiredError: 'token is expired',
  UserAlreadySignupError: 'failed to signup, user already signup',
  UserNotExistError: 'user not exist',
  WrongParameterError: 'wrong parameter',

  SuperAdminError: 'need super admin',
  AdminError: 'need admin',
  CanNotDeleteSelf: 'cant not delete self',
  NeedOrganizationIdError: 'need organization id',
  OrganizationNotFoundError: 'organization not found',
  RequireTokenError: 'require token error',
  NoPermissionsStoreFoundError: 'no permissions store found',
  RequestError: 'request error',
  YsRequestError: 'ys request error',
  NoStoreCamera: 'no store camera',
  NoPoiIdFound: 'no poiId found',
  NoStoreIdFound: 'no storeId found',
  NoStaFound: 'no sta found',
  StaHadExist: 'sta had exist',
  TimeoutError: 'time out error',
  PhysicalIdHadExist: 'physical had exist',
  CameraIdHadExist: 'camera id had exist',
  TagHadExist: 'tag id had exist',
  TagGoodIdHadExist: 'tag good had exist',
  FloorPlanMarkersNotExist: 'floor plan markers not exist',
};
