module.exports = {
  AdNotExistError:                              'ad not exist',
  AlreadyActivatedError:                        'already activated',
  AttachmentNotExistError:                      'attachment not exist',
  ClientNotExistError:                          'client not exist',
  CubePointAggregationFailedError:              'failed to aggregate cube point',
  CubePointNotExistError:                       'cube point not exist',
  DuplicateKeyError:                            'duplicate key',
  FileNotExistError:                            'file not exist',
  InternalError:                                'internal error, contact us',
  InvalidAppKeyError:                           'invalid appKey',
  InvalidAppSecretError:                        'invalid appSecret',
  InvalidClientKeyError:                        'invalid clientKey',
  InvalidClientSecretError:                     'invalid clientSecret',
  InvalidPasswordResetCodeError:                'invalid password reset code',
  InvalidTokenError:                            'invalid token',
  PasswordNotMatchError:                        'password not match',
  PendingPoiPullRequestExistsError:             'pending poi pull request exists',
  Success:                                      'success',
  SystemBusyError:                              'system busy, retry later',
  TokenExpiredError:                            'token is expired',
  UserAlreadySignupError:                       'failed to signup, user already signup',
  UserNotExistError:                            'user not exist',
  WrongParameterError:                          'wrong parameter'
};
